name: Run Unit Tests

on:
  push:
    branches: 
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      name: Run Checkout Dev 
      with:
        ref: dev
    - name: Run Install
      run: yarn install
    - name: Run Build
      run: yarn build
    - name: Run Test
      run: yarn test --watchAll=false
    - name: Run Checkout Mester and Rebase Dev
      run: |
        git status
        git checkout master
        git rebase dev
    - name: Push commit to master
      uses: ad-m/github-push-action@v.0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      env:
        CI: true
